export enum CUSTOMER_TABLE_HEADERS {
    ID = "ID",
    FULL_NAME = "FULL NAME",
    PHONE = "PHONE NO",
    STATUS = "STATUS",
    ACTIONS = "ACTIONS"
}


export enum USER_TABLE_HEADERS {
    ID ="ID",
    FULL_NAME ="FULL NAME",
    USERNAME = "USERNAME",
    ROLE = "ROLE",
    STATUS = "STATUS",
    ACTION = "ACTION"
}