export enum CUSTOMER_TABLE_HEADERS {
  ID = "ID",
  FULL_NAME = "FULL NAME",
  PHONE = "PHONE NO",
  STATUS = "STATUS",
  ACTIONS = "ACTIONS",
}

export enum USER_TABLE_HEADERS {
  ID = "ID",
  FULL_NAME = "FULL NAME",
  USERNAME = "USERNAME",
  ROLE = "ROLE",
  STATUS = "STATUS",
  ACTIONS = "ACTIONS",
}

export enum ITEM_TABLE_HEADERS {
  ID = "ID",
  NAME = "NAME",
  UNIT_PRICE = "UNIT PRICE",
  QUANTITY = "QUANTITY",
  STATUS = "STATUS",
  CATEGORY = "CATEGORY",
  ACTIONS = "ACTIONS",
}

export enum ITEM_CATEGORY_TABLE_HEADERS {
  ID = "ID",
  NAME = "NAME",
  ACTIONS = "ACTIONS",
}

export enum STOCK_TABLE_HEADERS {
  ID = "ID",
  NAME = "NAME",
  QUANTITY = "QUANTITY",
  CATEGORY = "CATEGORY",
  ACTIONS = "ACTIONS",
}

export enum STOCK_DETAIL_TABLE_HEADERS {
  ID = "ID",
  QUANTITY = "QUANTITY",
  CREATED_AT = "CREATED AT",
  UPDATED_AT = "UPDATED AT",
  ACTIONS = "ACTIONS",
}

export enum ORDER_TABLE_HEADERS {
  ID = "ID",
  TOTAL_PRICE = "TOTAL PRICE",
  CREATED_AT = "CREATED AT",
  UPDATED_AT = "UPDATED AT",
  STATUS = "STATUS",
  CUSTOMER = "CUSTOMER",
  CREATED_BY = "CREATED BY",
  ACTIONS = "ACTIONS",
}

export enum ORDERED_ITEM_TABLE_HEADERS {
  ID = "ID",
  ITEM = "ITEM",
  UNIT_PRICE = "UNIT PRICE",
  QUANTITY = "QUANTITY",
  ACTIONS = "ACTIONS",
}
